### **ravel can only flatten the data, but cant give it a shape**

In [ ]:
import numpy as np
# Create a 2x3 matrix
a = np.array([[1, 2, 3], 
              [4, 5, 6]])
# --- Using ravel() ---
# Automatically flattens it to [1, 2, 3, 4, 5, 6]
flat = a.ravel()        # 
# --- Using reshape() ---
# You must specify the new shape.
# To flatten with reshape, you have to use the "-1" trick:
reshaped_flat = a.reshape(-1) 
# But reshape is usually used for other things:
reshaped_3x2 = a.reshape(3, 2) 
# Becomes:
# [[1, 2],
#  [3, 4],
#  [5, 6]]

In [ ]:
print(a, '\n')
print(flat, '\n')
print(reshaped_flat, '\n')
print(reshaped_3x2, '\n')

[[1 2 3]
 [4 5 6]] 

[1 2 3 4 5 6] 

[1 2 3 4 5 6] 

[[1 2]
 [3 4]
 [5 6]] 



In [5]:
arr = np.array([[1, 2], [3, 4]])
r = arr.ravel()
r[0] = 99  # Change the flattened version
print(arr,'\n') 
print(r,'\n') 
# Output: [[99, 2], [3, 4]] <--- The original changed!

[[99  2]
 [ 3  4]] 

[99  2  3  4] 

